### ISSUE TITLE
Get flake8, isort, and Black working together

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/jade-truffle#23]
The other flake8 hook is deprecated, and the isort mirror is deprecated too. Updated `.pre-commit-config.yaml`:

```
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
```

`pyproject.toml`:
```
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
```

`.flake8`:
```
# flake8 doesn't support pyproject.toml:
# https://gitlab.com/pycqa/flake8/-/issues/428
[flake8]
max-line-length = 88
extend-ignore = E203, W503
```
